name: Add Help Wanted Issue Label

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  label-on-help-wanted:
    if: github.event.comment.body == '/help-wanted'
    runs-on: ubuntu-latest
    steps:
      - name: Add "help wanted" label
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['help wanted'],
            });
            console.log('Added label: help wanted');
